name: Ping

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: curl -s "https://full-stack-developer-assignment.onrender.com" > /dev/null