name: Ping

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the site to keep it alive
        run: curl -s "https://full-stack-developer-assignment.onrender.com" > /dev/null